language: go
go_import_path: go-hep.org/x/hep
os:
  - linux

dist: bionic

env:
 global:
   - ROOT_VERSION=6.22.02

cache:
 directories:
   - $HOME/gopath/pkg/mod
   - $HOME/root-${ROOT_VERSION}

git:
 depth: 10

matrix:
 fast_finish: true
 include:
   - go: main
     env:
       - TAGS="-tags=ci"
       - COVERAGE="-race"
       - GOPROXY="https://proxy.golang.org"
       - GO111MODULE="on"

sudo: required

notifications:
  email:
    on_success: always
    on_failure: always

before_install:
 - sudo apt-get install -qq pkg-config fuse libgles2-mesa-dev libxkbcommon-dev libxkbcommon-x11-dev
 - sudo modprobe fuse
 - sudo chmod 666 /dev/fuse
 - sudo chown root:$USER /etc/fuse.conf

before_script:
 - go run ./ci/install-cxx-root.go -root-version=${ROOT_VERSION} -o=${HOME}
 - source $HOME/root-${ROOT_VERSION}/bin/thisroot.sh
 - root.exe --version

script:
 - GOARCH=386   go install -v $TAGS,cross_compile ./...
 - GOARCH=amd64 go install -v $TAGS ./...
 - go run ./ci/run-tests.go -v $TAGS $COVERAGE
