build: off

image: Visual Studio 2019

stack: go 1.16

clone_folder: c:\gopath\src\go-hep.org\x\hep

cache:
  - '%LocalAppData%\go-build'

branches:
  only:
    - main

environment:
  GOPATH: c:\gopath
  PATH: '%GOPATH%\bin;%PATH%'

build_script:
  - go version
  - go get -v -t -tags purego ./...

test_script:
  - go test -tags purego ./...
