name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 1-5'

env:
  GOPROXY: "https://proxy.golang.org"
  ROOT_VERSION: "6.22.02"
  TAGS: "-tags=ci"
  COVERAGE: "-coverpkg=go-hep.org/x/hep/..."

jobs:

  build:
    name: Build
    strategy:
      matrix:
        go-version: [1.15.x, 1.14.x]
        platform: [ubuntu-latest, macos-latest]
        #platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
 
    - name: Cache-Go
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
 
    - name: Cache-ROOT
      uses: actions/cache@v1
      with:
        path: ~/root-${{ env.ROOT_VERSION }}
        key: ${{ runner.os }}-root-${{ env.ROOT_VERSION }}
        restore-keys: |
          ${{ runner.os }}-root-${{ env.ROOT_VERSION }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Linux packages
      if: matrix.platform == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -qq pkg-config libwayland-dev libx11-dev libx11-xcb-dev libxkbcommon-dev libxkbcommon-x11-dev libgles2-mesa-dev libegl1-mesa-dev libffi-dev libxcursor-dev
        go run ./ci/install-cxx-root.go -root-version=${ROOT_VERSION} -o=${HOME}
        source $HOME/root-${ROOT_VERSION}/bin/thisroot.sh
        root.exe --version
    
    - name: Build-Linux-32b
      if: matrix.platform == 'ubuntu-latest'
      run: |
        GOARCH=386   go install -v $TAGS,cross_compile ./...
    - name: Build-Linux-64b
      if: matrix.platform == 'ubuntu-latest'
      run: |
        GOARCH=amd64 go install -v $TAGS ./...       
    - name: Build-Windows
      if: matrix.platform == 'windows-latest'
      run: |
        go install -v $TAGS ./...
    - name: Build-Darwin
      if: matrix.platform == 'macos-latest'
      run: |
        go install -v $TAGS ./...
    - name: Test Linux
      if: matrix.platform == 'ubuntu-latest'
      run: |
        go run ./ci/run-tests.go $TAGS -race $COVERAGE
    - name: Test Windows
      if: matrix.platform == 'windows-latest'
      run: |
        go run ./ci/run-tests.go $TAGS
    - name: Test Darwin
      if: matrix.platform == 'macos-latest'
      run: |
        go run ./ci/run-tests.go $TAGS
    - name: Upload-Coverage
      if: matrix.platform == 'ubuntu-latest'
      uses: codecov/codecov-action@v1
